language: java
sudo: false
jdk:
 - openjdk11
cache:
  directories:
   - "$HOME/.cache"
jobs:
    - stage: deploy
      name: 'Deploy To Dev Environment'
      script:
       - mvn clean install
       - cp .travis.settings.xml $HOME/.m2/settings.xml
       - mvn deploy -DmuleDeploy -Dserver=$server -Dworkers=$workers -DworkerType=$workerType  -Denvironment=$environment -DmuleVersion=$muleVersion -DappName=$appName
      if: branch = develop
notifications:
    email:
        recipients:
            - admelalu@gmail.com
        on_success: always
        on_failure: always